# Generated by Django 3.1.5 on 2021-01-22 13:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('country_hq', django_countries.fields.CountryField(max_length=2)),
                ('locations', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='orgs.category')),
            ],
        ),
    ]
