# Generated by Django 3.1.5 on 2021-01-28 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_auto_20210128_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ('team_size',)},
        ),
        migrations.AddField(
            model_name='org',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
