# Generated by Django 3.1.5 on 2021-04-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20210413_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='country_HQ',
            new_name='country_hq',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='all_locations',
            new_name='locations',
        ),
    ]
