# Generated by Django 3.1.5 on 2021-04-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_auto_20210413_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='team_size',
            field=models.IntegerField(null=True),
        ),
    ]
