# Generated by Django 3.1.5 on 2021-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_auto_20210413_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='what_and_how',
            field=models.TextField(default='(Helping [stroke patients] to [recover] by [stimulating their nerves during a motor activity]', max_length=140),
        ),
        migrations.AlterField(
            model_name='org',
            name='primarily_concerned_with_brain_area',
            field=models.CharField(choices=[('frontal', 'Frontal lobe'), ('occipit', 'Occipital lobe'), ('cereb', 'Cerebellum'), ('temp', 'Temporal lobe'), ('pariet', 'Parietal lobe'), ('corpus', 'Corpus Callosum'), ('pitua', 'Pituitary gland'), ('stem', 'Brainstem'), ('periph', 'Peripheral nervous system')], max_length=7),
        ),
    ]
