# Generated by Django 3.1.5 on 2021-04-13 20:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20210413_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='primarily_concerned_with_brain_area',
        ),
        migrations.AddField(
            model_name='org',
            name='concerned_with_brain_area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('frontal', 'Frontal lobe'), ('occipit', 'Occipital lobe'), ('cereb', 'Cerebellum'), ('temp', 'Temporal lobe'), ('pariet', 'Parietal lobe'), ('corpus', 'Corpus Callosum'), ('pitua', 'Pituitary gland'), ('stem', 'Brainstem'), ('periph', 'Peripheral nervous system')], default='s', max_length=58),
        ),
        migrations.AlterField(
            model_name='org',
            name='what_and_how',
            field=models.TextField(default='(e.g. Helping [stroke patients] to [recover] by [stimulating their nerves during a motor activity])', max_length=140),
        ),
    ]
