# Generated by Django 3.1.5 on 2021-04-13 21:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('orgs', '0018_auto_20210413_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
