# Generated by Django 3.1.5 on 2021-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_org_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HigherOrderBrainFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='org',
            name='concerned_with_brain_area',
        ),
        migrations.AlterField(
            model_name='org',
            name='what_and_how',
            field=models.CharField(max_length=140),
        ),
    ]
