# Generated by Django 3.1.5 on 2021-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_auto_20210421_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='higherorderbrainfunctions',
            name='slug',
            field=models.CharField(default='temp', max_length=80),
            preserve_default=False,
        ),
    ]
