# Generated by Django 3.1.5 on 2021-04-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_higherorderbrainfunctions_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_BrainRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain_region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.brainregion')),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
            ],
        ),
        migrations.CreateModel(
            name='BrainRegion_HigherOrderBrainFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HO_brain_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.higherorderbrainfunctions')),
                ('brain_region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.brainregion')),
            ],
        ),
    ]
