# Generated by Django 3.1.5 on 2021-04-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_brainregion_higherorderbrainfunctions_org_brainregion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brainregion_higherorderbrainfunctions',
            unique_together={('brain_region_name', 'HO_brain_function')},
        ),
        migrations.AlterUniqueTogether(
            name='org_brainregion',
            unique_together={('org_name', 'brain_region_name')},
        ),
    ]
