# Generated by Django 3.1.5 on 2021-04-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_auto_20210421_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='higherorderbrainfunctions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
