# Generated by Django 3.1.5 on 2021-05-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_higherorderbrainfunctions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='all_locations',
        ),
    ]
