# Generated by Django 3.1.5 on 2021-06-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_remove_org_all_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='is_featured',
        ),
    ]
